# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1061e3ea64a18a6b00a0b59aa898c3d66c322ac7428e19b3af43d6b4679d5fe2c6fc1ea605cae7bdf5e4bd52d5c341ef47d98f2b2579edb9a64aa1b2d0aafa0c

test:
  secret_key_base: 028fe87f83aef5953d980bd1644e1d14cdee664998482d9bc5e9c69f4c89d00a5d766d08490f1af87f363607ed6df581a4285bb3bc69211ad289935a43f32e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
